// ─────────────────────────────────────────────────────────────────────────────
// Aura Enables — known provider catalog
// ─────────────────────────────────────────────────────────────────────────────
// Every provider Aura-code supports, with their API URLs, model mappings,
// and key env var names.  When the user picks a provider, this table tells
// the proxy everything it needs.

export interface ProviderDef {
  id: string;
  name: string;
  group?: string;
  variant?: string;
  adapter: 'openai' | 'anthropic';
  baseUrl: string;           // OpenAI-compatible base URL (chat/completions)
  keyPrompt: string;          // What to ask the user for
  keyHint: string;            // Example / format hint
  keyEnvVar: string;          // Env var name for reference
  defaultModel: string;       // Default target model
  models: string[];           // Available target models for this provider
  isCustom?: boolean;          // Ask for base URL and model at setup time
  notes?: string;             // Any special notes
}

export const PROVIDERS: ProviderDef[] = [
  {
    id: 'deepseek',
    name: 'DeepSeek',
    adapter: 'openai',
    baseUrl: 'https://api.deepseek.com/v1',
    keyPrompt: 'Enter your DeepSeek API key',
    keyHint: 'sk-... (starts with sk-)',
    keyEnvVar: 'DEEPSEEK_API_KEY',
    defaultModel: 'deepseek-chat',
    models: ['deepseek-chat', 'deepseek-reasoner'],
  },
  {
    id: 'opencode-zen',
    name: 'OpenCode Zen (free)',
    group: 'OpenCode',
    variant: 'Zen (free)',
    adapter: 'openai',
    baseUrl: 'https://open.opencode.chat/v1',
    keyPrompt: 'Enter your OpenCode Zen API key',
    keyHint: 'sk-... (get it from opencode.chat)',
    keyEnvVar: 'OPENCODE_ZEN_API_KEY',
    defaultModel: 'opencode-zen',
    models: ['opencode-zen'],
    notes: 'Free tier: 100 requests/day, 8K context',
  },
  {
    id: 'opencode-go',
    name: 'OpenCode Go',
    group: 'OpenCode',
    variant: 'Go',
    adapter: 'openai',
    baseUrl: 'https://go.opencode.chat/v1',
    keyPrompt: 'Enter your OpenCode Go API key',
    keyHint: 'sk-... (from opencode.chat)',
    keyEnvVar: 'OPENCODE_GO_API_KEY',
    defaultModel: 'opencode-go',
    models: ['opencode-go', 'opencode-max'],
  },
  {
    id: 'mimo-token',
    name: 'MiMo Token Plan',
    group: 'Xiaomi MiMo',
    variant: 'Token Plan',
    adapter: 'openai',
    baseUrl: 'https://token-plan-sgp.xiaomimimo.com/v1',
    keyPrompt: 'Enter your MiMo Token Plan API key',
    keyHint: 'tp-... (starts with tp-)',
    keyEnvVar: 'XIAOMI_API_KEY',
    defaultModel: 'mimo-v2-flash',
    models: ['mimo-v2-flash', 'mimo-v2.5-tts'],
    notes: 'Pre-paid token plan',
  },
  {
    id: 'mimo-payg',
    name: 'MiMo Pay-as-you-go',
    group: 'Xiaomi MiMo',
    variant: 'Pay as you go',
    adapter: 'openai',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    keyPrompt: 'Enter your MiMo PAYG API key',
    keyHint: 'sk-... (from xiaomimimo.com)',
    keyEnvVar: 'MIMO_PAYG_API_KEY',
    defaultModel: 'mimo-v2-flash',
    models: ['mimo-v2-flash', 'mimo-v2.5-tts'],
    notes: 'Pay-per-token billing',
  },
  {
    id: 'zhipu',
    name: 'Zhipu GLM',
    adapter: 'openai',
    baseUrl: 'https://api.z.ai/v1',
    keyPrompt: 'Enter your Zhipu (Z.ai) API key',
    keyHint: 'glm-... or sk-...',
    keyEnvVar: 'ZHIPU_API_KEY',
    defaultModel: 'glm-5.2-flash',
    models: ['glm-5.2-flash', 'glm-5.1-flash', 'glm-5-flash', 'glm-5.2', 'glm-5.1', 'glm-5'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    adapter: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    keyPrompt: 'Enter your OpenAI API key',
    keyHint: 'sk-proj-... (from platform.openai.com)',
    keyEnvVar: 'OPENAI_API_KEY',
    defaultModel: 'gpt-4o',
    models: ['gpt-4o', 'gpt-4o-mini', 'o3-mini', 'o4-mini', 'gpt-5.5', 'gpt-5.5-turbo', 'gpt-5.5-lite'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic (Claude)',
    adapter: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',  // Native — won't go through /chat/completions
    keyPrompt: 'Enter your Anthropic API key',
    keyHint: 'sk-ant-... (from console.anthropic.com)',
    keyEnvVar: 'ANTHROPIC_API_KEY',
    defaultModel: 'claude-sonnet-4-20250514',
    models: ['claude-sonnet-4-20250514', 'claude-3-5-haiku-latest'],
    notes: 'Anthropic uses its own API format, not OpenAI-compatible. Pass-through mode.',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    adapter: 'openai',
    baseUrl: 'https://openrouter.ai/api/v1',
    keyPrompt: 'Enter your OpenRouter API key',
    keyHint: 'sk-or-... (from openrouter.ai/keys)',
    keyEnvVar: 'OPENROUTER_API_KEY',
    defaultModel: 'deepseek-chat',
    models: ['deepseek-chat', 'gpt-4o', 'claude-sonnet-4', 'qwen-qwq-32b', 'google/gemini-2.5-flash', 'gemini-2.0-flash'],
    notes: 'Access many models through one API',
  },
  {
    id: 'groq',
    name: 'Groq (fast inference)',
    adapter: 'openai',
    baseUrl: 'https://api.groq.com/openai/v1',
    keyPrompt: 'Enter your Groq API key',
    keyHint: 'gsk_... (from console.groq.com)',
    keyEnvVar: 'GROQ_API_KEY',
    defaultModel: 'llama-3.3-70b-versatile',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'],
    notes: 'Very fast! Limited to small context models.',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    adapter: 'openai',
    baseUrl: 'https://api.x.ai/v1',
    keyPrompt: 'Enter your xAI API key',
    keyHint: 'xai-... (from console.x.ai)',
    keyEnvVar: 'XAI_API_KEY',
    defaultModel: 'grok-3',
    models: ['grok-3', 'grok-3-mini'],
  },
  {
    id: 'google',
    name: 'Google Gemini',
    adapter: 'openai',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',  // OpenAI-compatible wrapper
    keyPrompt: 'Enter your Google AI API key',
    keyHint: 'AIza... (from aistudio.google.com)',
    keyEnvVar: 'GOOGLE_API_KEY',
    defaultModel: 'gemini-2.5-flash',
    models: [
      'gemini-2.5-flash',
      'gemini-2.5-pro',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
      'gemini-1.5-pro',
      'gemini-1.5-flash',
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama (local)',
    adapter: 'openai',
    baseUrl: 'http://localhost:11434/v1',
    keyPrompt: 'No key needed (local) — press Enter to continue',
    keyHint: 'just press Enter',
    keyEnvVar: '',
    defaultModel: 'gemma3:12b',
    models: ['gemma3:12b', 'gemma3:4b', 'qwen2.5-coder:7b', 'llama3.2:3b', 'deepseek-r1:7b'],
    notes: 'Local. Free. Runs on your GPU.',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    adapter: 'openai',
    baseUrl: 'https://api.mistral.ai/v1',
    keyPrompt: 'Enter your Mistral API key',
    keyHint: 'from console.mistral.ai',
    keyEnvVar: 'MISTRAL_API_KEY',
    defaultModel: 'mistral-large-latest',
    models: ['mistral-large-latest', 'mistral-small-latest', 'codestral-latest'],
  },
  {
    id: 'together',
    name: 'Together AI',
    adapter: 'openai',
    baseUrl: 'https://api.together.xyz/v1',
    keyPrompt: 'Enter your Together API key',
    keyHint: 'from api.together.xyz',
    keyEnvVar: 'TOGETHER_API_KEY',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    models: [
      'meta-llama/Llama-3.3-70B-Instruct-Turbo',
      'deepseek-ai/DeepSeek-V3',
      'Qwen/Qwen2.5-Coder-32B-Instruct',
    ],
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    adapter: 'openai',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    keyPrompt: 'Enter your Fireworks API key',
    keyHint: 'fw_... or API key from fireworks.ai',
    keyEnvVar: 'FIREWORKS_API_KEY',
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    models: [
      'accounts/fireworks/models/llama-v3p3-70b-instruct',
      'accounts/fireworks/models/deepseek-v3',
      'accounts/fireworks/models/qwen2p5-coder-32b-instruct',
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    adapter: 'openai',
    baseUrl: 'https://api.perplexity.ai',
    keyPrompt: 'Enter your Perplexity API key',
    keyHint: 'pplx-... or API key from perplexity.ai',
    keyEnvVar: 'PERPLEXITY_API_KEY',
    defaultModel: 'sonar-pro',
    models: ['sonar-pro', 'sonar', 'sonar-reasoning-pro', 'sonar-reasoning'],
    notes: 'Search-grounded models; behavior differs from plain chat models.',
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    adapter: 'openai',
    baseUrl: 'https://api.cerebras.ai/v1',
    keyPrompt: 'Enter your Cerebras API key',
    keyHint: 'from cloud.cerebras.ai',
    keyEnvVar: 'CEREBRAS_API_KEY',
    defaultModel: 'llama-3.3-70b',
    models: ['llama-3.3-70b', 'llama3.1-8b'],
    notes: 'Fast OpenAI-compatible inference.',
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    adapter: 'openai',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    keyPrompt: 'Enter your NVIDIA API key',
    keyHint: 'from build.nvidia.com',
    keyEnvVar: 'NVIDIA_API_KEY',
    defaultModel: 'meta/llama-3.1-70b-instruct',
    models: ['meta/llama-3.1-70b-instruct', 'mistralai/mixtral-8x7b-instruct-v0.1'],
  },
  {
    id: 'dashscope',
    name: 'Alibaba DashScope',
    adapter: 'openai',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    keyPrompt: 'Enter your DashScope API key',
    keyHint: 'sk-... from Alibaba Cloud Model Studio',
    keyEnvVar: 'DASHSCOPE_API_KEY',
    defaultModel: 'qwen-plus',
    models: ['qwen-plus', 'qwen-max', 'qwen-turbo', 'qwen-coder-plus'],
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI (Kimi)',
    adapter: 'openai',
    baseUrl: 'https://api.moonshot.ai/v1',
    keyPrompt: 'Enter your Moonshot API key',
    keyHint: 'sk-... from platform.moonshot.ai',
    keyEnvVar: 'MOONSHOT_API_KEY',
    defaultModel: 'kimi-k2-0711-preview',
    models: ['kimi-k2-0711-preview', 'moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
  },
  {
    id: 'baichuan',
    name: 'Baichuan',
    adapter: 'openai',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    keyPrompt: 'Enter your Baichuan API key',
    keyHint: 'from platform.baichuan-ai.com',
    keyEnvVar: 'BAICHUAN_API_KEY',
    defaultModel: 'Baichuan4',
    models: ['Baichuan4', 'Baichuan3-Turbo', 'Baichuan3-Turbo-128k'],
  },
  {
    id: 'custom-openai',
    name: 'Custom OpenAI-compatible',
    adapter: 'openai',
    baseUrl: '',
    keyPrompt: 'Enter your API key',
    keyHint: 'Any provider exposing /chat/completions',
    keyEnvVar: 'CUSTOM_OPENAI_API_KEY',
    defaultModel: '',
    models: [],
    isCustom: true,
    notes: 'Use this for providers not listed yet.',
  },
];

export function findProvider(id: string): ProviderDef | undefined {
  return PROVIDERS.find(p => p.id === id);
}
